### ISSUE TITLE
vue 3.5 reactive `props` destructure 

### ISSUE THREAD

**Issue by mnenie** [mnenie/jenda#63]
@sv022 что думаешь насчет новшества 3.5 версии с деструктуризацией пропсов без потери реактивности ? на мой взгляд надо на нее переписывать (придерживаться одного стиля) но тут дело удобства

`const { foo = 'hello' } = defineProps<{ foo?: string }>()`

замена тому же макросу `withDefaults` в на мой взгляд более удобной форме 
где под капотом преобразуется в `props.anyProp`

вот работа с макросом:

`const props = withDefaults(defineProps<Props>(), {
  msg: 'hello',
  labels: () => ['one', 'two']
})`

также у него стоит warning в recommended -> отключается правилом `vue/require-default-prop`: `off`,

есть коммит: [b235501](https://github.com/mnenie/jenda/commit/b235501eed122260a9edea0422300ed99d9d241d) который недавно я запушил в ветку `storybook` чекни `UiButton.vue` там я как раз поменял реализацию

**Comment by sv022** [comment]
Ну согласен, на мой взгляд намного удобнее чем макрос. Тогда во всех файлах так меняем?

**Comment by mnenie** [comment]
> Ну согласен, на мой взгляд намного удобнее чем макрос. Тогда во всех файлах так меняем?

да, давай я закрою #61 и зарезолвю эту ишью тоже (сегодня-завтра)

**Comment by mnenie** [comment]
@sv022 зарезолвил
если найдутся еще где то моменты с `withDefaults` будем по ходу дела править
